include: package:lint/analysis_options.yaml

linter:
  rules:
    errors:
      parameter_assignments: error
      missing_required_param: error
      missing_return: error

    sort_constructors_first: true

    public_member_api_docs: true

    always_specify_types: true

    lines_longer_than_80_chars: true
