name: chat_app
description: A new Flutter application.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_hooks: ^0.16.0
  hooks_riverpod: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.0.3

flutter:
  uses-material-design: true
